variables:
    DOCKER_REGISTRY: "gitlab-registry.cern.ch/alice-its3-wp3/moss-testing/docker"

stages:
    - build

default:
    before_script:
        - hostname -I
        - whoami
        - pwd
        - which python
        - python --version
        - echo $PATH


build-centos:
    stage: build
    when: manual
    needs: []
    dependencies: []
    cache: []
    image: ${DOCKER_REGISTRY}/fpga-lint
    script:
        # Get Rust toolchain
        - curl https://sh.rustup.rs -sSf | bash -s -- -y
        # Add cargo to path
        - PATH="/root/.cargo/bin:${PATH}"
        - python -m pip install maturin
        - maturin build
    artifacts:
        name: "${CI_COMMIT_SHA}"
        paths:
        - $CI_PROJECT_DIR/target/
